theme: jekyll-theme-minimal
title: Magdalena Reilly Sendal # your name (or website title) here
#logo: "/assets/img/logo_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <div class="logo-container">
    <img src="assets/img/logo3.png" alt="?"/>
  </div>
  <br><center>
  Highly skilled <b>Data Engineer</b> with 5+ years experience
  </center><br><br>
  <b> Contact me: </b>
  <br><br>

  <div class="contact-panel">
  <a href="mailto:magda.sendal@gmail.com">
      <img class="contact-icon" src="assets/img/gmail.png">
      <span>magda.sendal@gmail.com</span>
  </a>

  <a href="https://www.linkedin.com/in/magdalena-sendal-b29b6531/">
      <img class="contact-icon" src="assets/img/linkedin.png">
      <span>linkedin.com/in/magdalena-sendal-b29b6531/</span>
  </a>

  <a href="https://github.com/zelatyna">
      <img class="contact-icon" src="assets/img/github.png">
      <span>github.com/zelatyna</span>
  </a>
  </div>
  <br><br>

  <button class = "print-button" onclick="window.print()">Print me</button>

show_downloads: false
google_analytics: 153979434
